exclude: [README.md]

markdown: redcarpet
redcarpet:
  extensions: [ "tables" ]

baseurl: /storm

issue_base_url: "https://issues.infn.it/browse/"
website_base_url: "http://italiangrid.github.io/storm"
repo_base_url: "https://github.com/italiangrid"

sysadmin_guide_version: 1.11.4
functional_description_version: 1.11.2
webdav_guide_version: 3.0.1

storm_components:
    - name: StoRM Backend
      package: storm-backend-server
      latest: 1.11.4
      new: true
      repo: StoRM
      visibility: show
    - name: StoRM Frontend
      package: storm-frontend-server
      latest: 1.8.4
      new: false
      repo: StoRM emi
      visibility: show
    - name: StoRM GridHTTPs Server
      package: storm-gridhttps-server
      latest: 3.0.1
      new: true
      repo: StoRM
      visibility: show
    - name: StoRM native libs
      package: storm-native-libs
      latest: 1.0.2
      new: false
      repo: StoRM emi
      visibility: hide
    - name: StoRM dynamic info
      package: storm-dynamic-info-provider
      latest: 1.7.6
      new: false
      repo: StoRM emi
      visibility: hide
    - name: StoRM client
      package: storm-srm-client
      latest: 1.6.1
      new: false
      repo: StoRM emi
      visibility: hide
    - name: StoRM GridHTTPs plugin
      package: storm-gridhttps-plugin
      latest: 1.1.0
      new: false
      repo: StoRM emi
      visibility: hide
    - name: StoRM GridFTP
      package: storm-gridftp-dsi
      latest: 1.2.0
      new: false
      repo: StoRM emi
      visibility: hide
    - name: YAIM StoRM
      package: yaim-storm
      latest: 4.3.5
      new: true
      repo: StoRM
      visibility: hide
      
authors:
  andrea:
    display_name: Andrea Ceccanti
    gravatar: f371f6284e5f3b10c555a24fd728a1ef    
    email: andrea.ceccanti@cnaf.infn.it
    github: andreaceccanti
  valerio:
    display_name: Valerio Venturi
    gravatar: 25170d7bd06dd4d753053e12888d1bb0    
    email: valerio.venturi@cnaf.infn.it
    github: valerioventuri
  daniele:
    display_name: Daniele Andreotti
    email: daniele.andreotti@cnaf.infn.it
    github: dandreotti
  enrico:
    display_name: Enrico Vianello
    email: enrico.vianello@cnaf.infn.it
    gravatar: 4f496230f3e42d606024e16c5f389611
    github: enricovianello
