exclude: [README.md]

markdown: redcarpet
redcarpet:
  extensions: [ "tables" ]

baseurl: /storm

issue_base_url: "https://issues.infn.it/browse/"
website_base_url: "http://italiangrid.github.io/storm"
repo_base_url: "https://github.com/italiangrid"

sysadmin_guide_version: 1.11.4
functional_description_version: 1.11.2
webdav_guide_version: 3.0.1

