exclude: [README.md]

markdown: redcarpet
redcarpet:
  extensions: [ "tables" ]

issue_base_url: "https://issues.infn.it/browse/"
website_base_url: "http://italiangrid.github.io/storm"
repo_base_url: "https://github.com/italiangrid"

storm_latest_version: "1.11.2"

storm_released_versions:
    - version: "1.11.2"
      title: "StoRM v.1.11.2"
      date: "20.07.2013"
      description: "This was the second update for StoRM in EMI-3"
      notes:
          - name: "StoRM-v1.11.2"
    - version: "1.11.1"
      title: "StoRM v.1.11.1"
      date: "03.06.2013"
      description: "This was the first update for StoRM in EMI-3"
      notes:
          - name: "StoRM-v1.11.1"

storm_old_versions:
    - version: "1.11.0"
      date: "11.03.2013"
      description: "This was the StoRM released in EMI-3 - _deprecated_"
      notes: "http://www.eu-emi.eu/releases/emi-3-montebianco/products/-/asset_publisher/5dKm/content/storm-se-2"
    - version: "1.10.0"
      date: "20.07.2012"
      description: "This was the first update for StoRM in EMI-2"
      notes: "http://www.eu-emi.eu/emi-2-matterhorn/updates/-/asset_publisher/9AgN/content/update-1-20-07-2012#StoRM_SE_v_1_10_0_task_30816"
    - version: "1.9.0"
      date: "21.05.2012"
      description: "This was the StoRM released with EMI-2"
      notes: "http://www.eu-emi.eu/emi-2-matterhorn-products/-/asset_publisher/B4Rk/content/storm-se-1"

authors:
  andrea:
    display_name: Andrea Ceccanti
    gravatar: f371f6284e5f3b10c555a24fd728a1ef    
    email: andrea.ceccanti@cnaf.infn.it
    github: andreaceccanti
  valerio:
    display_name: Valerio Venturi
    gravatar: 25170d7bd06dd4d753053e12888d1bb0    
    email: valerio.venturi@cnaf.infn.it
    github: valerioventuri
  daniele:
    display_name: Daniele Andreotti
    email: daniele.andreotti@cnaf.infn.it
  enrico:
    display_name: Enrico Vianello
    email: enrico.vianello@cnaf.infn.it
    gravatar: 4f496230f3e42d606024e16c5f389611
    github: enricovianello